# Generated by Django 4.1.5 on 2023-01-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_image_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PostImage',
        ),
    ]
