# Generated by Django 4.1.5 on 2023-03-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_project_alter_member_image_alter_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='map',
        ),
    ]
