# Generated by Django 4.1.5 on 2023-03-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_project_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='map',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
