# Generated by Django 4.1.5 on 2023-03-23 12:53

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_project_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('content', models.TextField()),
                ('goal', models.IntegerField()),
                ('raised', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='rotary/donations')),
                ('categories', models.ManyToManyField(to='base.category')),
            ],
        ),
    ]
